spring.datasource.url=jdbc:postgresql://db.cikelyfguxkamdvewpfm.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=FfNpjqth5Zej4psQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=MyResumeBuilderSecretKeyForJwtAuthentication123456789
jwt.expiration=86400000
